[book]
authors = ["Robert N. M. Watson"]
language = "en"
multilingual = false
src = "src"
title = "CheriBSD 23.11 new features tutorial"

[output.html]
git-repository-url = "https://github.com/CTSRD-CHERI/cheribsd-23-11-tutorial"
site-url = "/cheribsd-23-11-tutorial/"
